---
- name: Create a local backup directory
  ansible.builtin.file:
    path: /home/{{ user }}/backup-drive
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0755'
- name: Install Rclone for offsite backup
  become: true
  ansible.builtin.apt:
    name: rclone
    state: present
- name: Create Rclone config directory
  ansible.builtin.file:
    path: /home/{{ user }}/.config/rclone
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0755'
- name: Copy Rclone config file
  ansible.builtin.copy:
    force: false
    src: rclone.conf
    dest: /home/{{ user }}/.config/rclone/rclone.conf
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0644'
- name: Install borg
  become: true
  ansible.builtin.apt:
    name: borgbackup
    state: present
- name: Init Borg Repo
  ansible.builtin.command:
    cmd: borg init -e none /home/{{ user }}/backup-drive/{{ backup_directory }}
    creates: /home/{{ user }}/backup-drive/{{ backup_directory }}/config
- name: Create logs directory
  ansible.builtin.file:
    path: /home/{{ user }}/logs
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0755'
