---
- name: Update Server Packages
  become: true
  hosts: server
  vars_files:
    - ../../vars.yml
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
    - name: Upgrade all packages on servers
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true
    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false
    - name: Reboot the box if kernel updated
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists
