---
services:
  deluge:
    image: lscr.io/linuxserver/deluge:2.2.0
    container_name: deluge
    restart: unless-stopped
    labels:
      - "traefik.http.routers.deluge.rule=Host(`deluge.noste.xyz`)"
      - "traefik.http.routers.deluge.entrypoints=websecure"
      - "traefik.http.routers.deluge.tls=true"
      - "traefik.http.routers.deluge.tls.certresolver=defaultresolver"
      - "traefik.http.routers.deluge.middlewares=oauth"
      - "traefik.http.services.deluge.loadbalancer.server.port=8112"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - DELUGE_LOGLEVEL=error
    volumes:
      - /home/noste/deluge/config:/config
      - /home/noste/deluge/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
    networks:
      - public_network

networks:
  public_network:
    name: reverse_proxy_network
    external: true
