---
- name: Create config directory
  ansible.builtin.file:
    path: /home/{{ user }}/{{ service_name }}
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0755'
- name: Copy docker compose files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ user }}/{{ service_name }}/
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0644'
  with_fileglob:
    - docker-compose/{{ service_name }}/.*
    - docker-compose/{{ service_name }}/*
