---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

# Optional: Use external configuration file.
# Using this will ignore remaining config in this file
# externalConfig: https://example.com/server-luci/config.yaml

title: "Home dashboard"
subtitle: "Personal home server ❤️"
documentTitle: "Home Server" # Customize the browser tab text
logo: "assets/logo.png"
header: true # Set to false to hide the header
# Optional: Different hotkey for search, defaults to "/"
# hotkey:
#   search: "Shift"
footer: false

columns: "auto" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: false # https://github.com/bastienwirtz/homer/issues/468
# Set the default layout and color scheme
defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'
theme: default # 'default' or one of the themes available in 'src/assets/themes'.
stylesheet:
  - 'assets/style.css'

# Optional message
# message:
  # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
  # mapping: # allows to map fields from the remote format to the one expected by Homer
  #   title: 'id' # use value from field 'id' as title
  #   content: 'value' # value from field 'value' as content
  # refreshInterval: 10000 # Optional: time interval to refresh message
  #
  # Real example using chucknorris.io for showing Chuck Norris facts as messages:
  # url: https://api.chucknorris.io/jokes/random
  # mapping:
  #   title: 'id'
  #   content: 'value'
  # refreshInterval: 10000
  # style: "is-warning"
  # title: "Optional message!"
  # icon: "fa fa-exclamation-triangle"
  # content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Server Config"
    icon: "fab fa-gitlab"
    url: "https://gitlab.com/Noste/ansible-home-server/"
    target: "_blank" 
  - name: "Awesome Selfhosted"
    icon: "fab fa-github"
    url: "https://github.com/awesome-selfhosted/awesome-selfhosted"
    target: "_blank" 
  - name: "Notion docs [coming soon]"
    icon: "fas fa-book"
    url: "https://notion.com"
  # this will link to a second homer page that will load config from page2.yml and keep default config values as in config.yml file
  # see url field and assets/page.yml used in this example:
  # - name: "Second Page"
  #   icon: "fas fa-file-alt"
  #   url: "#page2"

# Services
# First level array represents a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Infrastructure Apps"
    icon: "fas fa-hammer"
    items:
      - name: "Traefik"
        logo: "assets/images/traefik.png"
        url: "https://traefik.noste.xyz"
        target: "_blank"
      - name: "Pi-hole"
        logo: "assets/images/pihole.png"
        url: "http://pihole.noste.xyz/admin"
        target: "_blank"
      - name: "Asus Router"
        logo: "assets/images/asus.png"
        url: "http://192.168.1.1/"
        target: "_blank"
      - name: "DNS"
        url: "https://dash.cloudflare.com/6f94b8d45d87668a36c6588774bab879/noste.xyz/dns/records"
        target: "_blank"
        logo: "assets/images/DNS.png"
      - name: "Netdata"
        url: "https://netdata.noste.xyz"
        target: "_blank"
        logo: "assets/images/netdata.png"
  - name: "Media"
    icon: "fa-solid fa-photo-film"
    items:
      - name: "Jellyfin"
        subtitle: "[Coming Soon]"
        logo: "assets/images/jellyfin.png"
      - name: "Openbooks"
        subtitle: "[Coming Soon]"
        icon: "fa-solid fa-book-open"
      - name: "Deluge"
        subtitle: "[Coming Soon]"
        logo: "assets/images/deluge.png"
      - name: "Radarr"
        subtitle: "[Coming Soon]"
        logo: "assets/images/radarr.png"
      - name: "Sonarr"
        subtitle: "[Coming Soon]"
        logo: "assets/images/sonarr.png"
  - name: "Cloud Services"
    icon: "fa-solid fa-cloud"
    items:
      - name: "Immich"
        logo: "assets/images/immich.png"
        url: "https://photos.noste.xyz/"
        target: "_blank"
      - name: "Nextcloud"
        subtitle: "[Coming Soon]"
        logo: "assets/images/nextcloud.png"
      - name: "Vaultwarden"
        subtitle: "[Coming Soon]"
        logo: "assets/images/vaultwarden.png"
# Optional: Proxy / hosting option
proxy:
  useCredentials: false # send cookies & authorization headers when fetching service specific data. Set to `true` if you use an authentication proxy. Can be overrided on service level. 
